# Generated by Django 2.0.7 on 2018-10-03 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_name', models.CharField(choices=[('Unclassified', 'unclassified'), ('PUBLIC', 'public'), ('CONFIDENTIAL', 'confidential'), ('PROTECTED A', 'protected_a'), ('PROTECTED B', 'protected_b'), ('PROTECTED C', 'protected_c')], max_length=50)),
                ('datasource_description', models.CharField(max_length=100)),
                ('schema', models.CharField(max_length=50)),
                ('table_name', models.CharField(max_length=50)),
                ('column_name', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, max_length=40)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending')], max_length=15)),
                ('summary', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='classification_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_name', models.CharField(choices=[('Unclassified', 'unclassified'), ('PUBLIC', 'public'), ('CONFIDENTIAL', 'confidential'), ('PROTECTED A', 'protected_a'), ('PROTECTED B', 'protected_b'), ('PROTECTED C', 'protected_c')], max_length=50)),
                ('count', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='classification_exception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classy.classification')),
            ],
        ),
        migrations.CreateModel(
            name='classification_logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('action_flag', models.SmallIntegerField()),
                ('n_classification', models.CharField(choices=[('Unclassified', 'unclassified'), ('PUBLIC', 'public'), ('CONFIDENTIAL', 'confidential'), ('PROTECTED A', 'protected_a'), ('PROTECTED B', 'protected_b'), ('PROTECTED C', 'protected_c')], max_length=50)),
                ('o_classification', models.CharField(choices=[('Unclassified', 'unclassified'), ('PUBLIC', 'public'), ('CONFIDENTIAL', 'confidential'), ('PROTECTED A', 'protected_a'), ('PROTECTED B', 'protected_b'), ('PROTECTED C', 'protected_c')], max_length=50)),
                ('user_id', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=15)),
                ('approved_by', models.CharField(max_length=50)),
                ('classy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classy.classification')),
            ],
        ),
        migrations.CreateModel(
            name='classification_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_name', models.CharField(max_length=50)),
                ('schema', models.CharField(max_length=50)),
                ('table_name', models.CharField(max_length=50)),
                ('column_name', models.CharField(max_length=50)),
                ('datasource_description', models.CharField(max_length=100)),
                ('action_flag', models.SmallIntegerField()),
                ('o_classification', models.CharField(max_length=50)),
                ('classy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classy.classification')),
            ],
        ),
        migrations.CreateModel(
            name='classification_review_groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datasource', models.CharField(max_length=100)),
                ('schema', models.CharField(blank=True, max_length=50)),
                ('table', models.CharField(blank=True, max_length=50)),
                ('column', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='classification_review',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classy.classification_review_groups'),
        ),
    ]
