# Generated by Django 2.0.10 on 2019-01-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='notes',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='classification',
            name='masking',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
