# Generated by Django 2.0.8 on 2018-12-20 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completed_task',
            options={'default_permissions': ()},
        ),
    ]
