# Generated by Django 2.0.1 on 2018-01-29 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
