# Generated by Django 2.0.1 on 2018-01-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0003_auto_20180130_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='category',
            field=models.CharField(default='not_provided', max_length=40),
        ),
    ]
