# Generated by Django 2.1.8 on 2019-05-29 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0005_auto_20190528_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completed_task',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.DeleteModel(
            name='completed_task',
        ),
        migrations.DeleteModel(
            name='task',
        ),
    ]
