# Generated by Django 2.0.1 on 2018-02-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0006_classification_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='created_by',
            field=models.CharField(max_length=50, null='True'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
