# Generated by Django 2.0.1 on 2018-02-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0007_auto_20180206_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='classification_logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classy_id', models.IntegerField()),
                ('action_time', models.DateTimeField(auto_now=True)),
                ('action_flag', models.SmallIntegerField()),
                ('n_classification', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
