# Generated by Django 2.0.1 on 2018-02-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0008_classification_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification_logs',
            name='user_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
