# Generated by Django 2.0.1 on 2018-02-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0009_classification_logs_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='created_by',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
