# Generated by Django 2.1.8 on 2019-06-20 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0009_auto_20190619_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationlogs',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classy.Application'),
        ),
        migrations.AddField(
            model_name='classificationreview',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classy.Application'),
        ),
        migrations.AddField(
            model_name='classificationreview',
            name='protected_type',
            field=models.CharField(blank=True, choices=[('PA', 'Protected A'), ('PB', 'Protected B'), ('PC', 'Protected C')], max_length=2),
        ),
        migrations.AlterField(
            model_name='classificationlogs',
            name='classy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classy.Classification'),
        ),
        migrations.AlterField(
            model_name='classificationreview',
            name='classification',
            field=models.CharField(blank=True, choices=[('UN', 'Unclassified'), ('PU', 'Public'), ('PE', 'Personal'), ('CO', 'Confidential')], max_length=2),
        ),
        migrations.AlterField(
            model_name='classificationreview',
            name='classy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classy.Classification'),
        ),
        migrations.AlterField(
            model_name='classificationreview',
            name='flag',
            field=models.SmallIntegerField(choices=[(0, 'Delete'), (1, 'Modify'), (2, 'Create')]),
        ),
    ]
