# Generated by Django 2.0.1 on 2018-02-16 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0010_auto_20180215_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification_logs',
            name='o_classification',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
