# Generated by Django 2.0.1 on 2018-02-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0011_classification_logs_o_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='category',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='classification',
            name='column_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='classification',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='classification',
            name='datasource_description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='classification',
            name='schema',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='classification',
            name='table_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='classification_logs',
            name='action_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
