# Generated by Django 2.0.1 on 2018-03-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0012_auto_20180219_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='classification_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_name', models.CharField(choices=[('CONFIDENTIAL', 'confidential'), ('PUBLIC', 'public'), ('Unclassified', 'unclassified'), ('PROTECTED A', 'protected_a'), ('PROTECTED B', 'protected_b'), ('PROTECTED C', 'protected_c')], default='unclassified', max_length=50)),
                ('schema', models.CharField(max_length=50, null=True)),
                ('table_name', models.CharField(max_length=50, null=True)),
                ('column_name', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(max_length=40, null=True)),
                ('datasource_description', models.CharField(max_length=200, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('action_flag', models.SmallIntegerField()),
                ('o_classification', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='classification',
            name='classification_name',
            field=models.CharField(choices=[('CONFIDENTIAL', 'confidential'), ('PUBLIC', 'public'), ('Unclassified', 'unclassified'), ('PROTECTED A', 'protected_a'), ('PROTECTED B', 'protected_b'), ('PROTECTED C', 'protected_c')], default='confidential', max_length=50),
        ),
    ]
