# Generated by Django 2.0.1 on 2018-03-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0013_auto_20180302_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='classification_name',
            field=models.CharField(choices=[('Unclassified', 'unclassified'), ('PUBLIC', 'public'), ('CONFIDENTIAL', 'confidential'), ('PROTECTED A', 'protected_a'), ('PROTECTED B', 'protected_b'), ('PROTECTED C', 'protected_c')], default='confidential', max_length=50),
        ),
        migrations.AlterField(
            model_name='classification_review',
            name='classification_name',
            field=models.CharField(choices=[('Unclassified', 'unclassified'), ('PUBLIC', 'public'), ('CONFIDENTIAL', 'confidential'), ('PROTECTED A', 'protected_a'), ('PROTECTED B', 'protected_b'), ('PROTECTED C', 'protected_c')], default='unclassified', max_length=50),
        ),
    ]
