# Generated by Django 2.1.8 on 2019-06-12 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0013_auto_20190611_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='classification',
            field=models.CharField(choices=[('UN', 'Unclassified'), ('PU', 'Public'), ('PE', 'Personal'), ('CO', 'Confidential')], default='UN', max_length=2),
        ),
        migrations.AlterField(
            model_name='classification',
            name='protected_type',
            field=models.CharField(blank=True, choices=[('PA', 'Protected A'), ('PB', 'Protected B'), ('PC', 'Protected C')], max_length=2),
        ),
        migrations.AlterField(
            model_name='classificationcount',
            name='classification',
            field=models.CharField(choices=[('UN', 'Unclassified'), ('PU', 'Public'), ('PE', 'Personal'), ('CO', 'Confidential')], max_length=2),
        ),
        migrations.AlterField(
            model_name='classificationlogs',
            name='classification',
            field=models.CharField(blank=True, choices=[('UN', 'Unclassified'), ('PU', 'Public'), ('PE', 'Personal'), ('CO', 'Confidential')], max_length=2),
        ),
        migrations.AlterField(
            model_name='classificationlogs',
            name='classy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classy.Classification'),
        ),
        migrations.AlterField(
            model_name='classificationlogs',
            name='protected_type',
            field=models.CharField(blank=True, choices=[('PA', 'Protected A'), ('PB', 'Protected B'), ('PC', 'Protected C')], max_length=2),
        ),
        migrations.AlterField(
            model_name='classificationreview',
            name='classification',
            field=models.CharField(choices=[('UN', 'Unclassified'), ('PU', 'Public'), ('PE', 'Personal'), ('CO', 'Confidential')], max_length=2),
        ),
        migrations.AlterField(
            model_name='classificationreview',
            name='classy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classy.Classification'),
        ),
    ]
