# Generated by Django 2.0.1 on 2018-03-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0015_auto_20180305_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classification_review',
            old_name='creation_date',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='classification_review',
            old_name='created_by',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='classification_review',
            name='category',
        ),
        migrations.AlterField(
            model_name='classification_logs',
            name='state',
            field=models.CharField(default='Active', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classification_review',
            name='classification_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='classification_review',
            name='datasource_description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
