# Generated by Django 2.0.1 on 2018-03-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0016_auto_20180306_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification_review',
            name='classy_id',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
