# Generated by Django 2.0.1 on 2018-03-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0017_classification_review_classy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='column_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classification',
            name='created_by',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classification',
            name='datasource_description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classification',
            name='schema',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classification',
            name='state',
            field=models.CharField(choices=[('Active', 0), ('Inactive', 1), ('Pending Review', 2)], default='Active', max_length=15),
        ),
        migrations.AlterField(
            model_name='classification',
            name='table_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classification_logs',
            name='user_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classification_review',
            name='column_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classification_review',
            name='datasource_description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classification_review',
            name='schema',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classification_review',
            name='table_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classification_review',
            name='user',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
