# Generated by Django 2.0.1 on 2018-03-06 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0018_auto_20180306_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classification_review',
            name='classy_id',
        ),
    ]
