# Generated by Django 2.0.1 on 2018-03-06 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0019_remove_classification_review_classy_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classification_logs',
            name='action_flag',
        ),
        migrations.RemoveField(
            model_name='classification_logs',
            name='classy_id',
        ),
    ]
