# Generated by Django 2.0.1 on 2018-03-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0021_auto_20180306_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='state',
            field=models.CharField(choices=[('Active', 0), ('Inactive', 1), ('Pending Review', 2)], default=0, max_length=15),
        ),
    ]
