# Generated by Django 2.0.1 on 2018-03-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0022_auto_20180306_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='column_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='classification',
            name='created_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='classification',
            name='datasource_description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='classification',
            name='schema',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='classification',
            name='table_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='classification_logs',
            name='state',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='classification_logs',
            name='user_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='classification_review',
            name='classification_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='classification_review',
            name='column_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='classification_review',
            name='datasource_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='classification_review',
            name='schema',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='classification_review',
            name='table_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='classification_review',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
