# Generated by Django 2.0.1 on 2018-03-06 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0026_auto_20180306_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='classification_review_groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='classification_review',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='classification_review',
            name='user',
        ),
        migrations.AlterField(
            model_name='classification_review',
            name='classy_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classy.classification'),
        ),
    ]
