# Generated by Django 2.0.1 on 2018-03-06 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0027_auto_20180306_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification_review',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classy.classification_review_groups'),
        ),
    ]
