# Generated by Django 2.0.1 on 2018-03-06 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0028_classification_review_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classification_logs',
            old_name='classy_id',
            new_name='classy',
        ),
        migrations.RenameField(
            model_name='classification_review',
            old_name='classy_id',
            new_name='classy',
        ),
    ]
