# Generated by Django 2.0.1 on 2018-03-06 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0029_auto_20180306_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classification_review',
            old_name='group_id',
            new_name='group',
        ),
    ]
