# Generated by Django 2.0.1 on 2018-04-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0030_auto_20180306_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='state',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending')], max_length=15, null=True),
        ),
    ]
