# Generated by Django 2.0.4 on 2018-04-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0031_auto_20180408_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='classification_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_name', models.CharField(choices=[('Unclassified', 'unclassified'), ('PUBLIC', 'public'), ('CONFIDENTIAL', 'confidential'), ('PROTECTED A', 'protected_a'), ('PROTECTED B', 'protected_b'), ('PROTECTED C', 'protected_c')], max_length=50, null=True)),
                ('count', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
