# Generated by Django 2.0.4 on 2018-04-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0032_classification_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification_count',
            name='date',
            field=models.DateField(),
        ),
    ]
