# Generated by Django 2.0.4 on 2018-04-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0033_auto_20180413_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification_logs',
            name='approved_by',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
