# Generated by Django 2.0.4 on 2018-05-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0035_classification_exception'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='summary',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
