# Generated by Django 2.0.7 on 2018-09-06 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0037_auto_20180906_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='column_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='classification',
            name='created_by',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='classification',
            name='datasource_description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='classification',
            name='schema',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='classification',
            name='state',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending')], max_length=15),
        ),
        migrations.AlterField(
            model_name='classification',
            name='table_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='classification_count',
            name='classification_name',
            field=models.CharField(choices=[('Unclassified', 'unclassified'), ('PUBLIC', 'public'), ('CONFIDENTIAL', 'confidential'), ('PROTECTED A', 'protected_a'), ('PROTECTED B', 'protected_b'), ('PROTECTED C', 'protected_c')], max_length=50),
        ),
        migrations.AlterField(
            model_name='classification_exception',
            name='classy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classy.classification'),
        ),
        migrations.AlterField(
            model_name='classification_logs',
            name='approved_by',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='classification_logs',
            name='classy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classy.classification'),
        ),
        migrations.AlterField(
            model_name='classification_logs',
            name='n_classification',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='classification_logs',
            name='o_classification',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='classification_logs',
            name='state',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='classification_logs',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='classification_review',
            name='classification_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='classification_review',
            name='column_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='classification_review',
            name='datasource_description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='classification_review',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classy.classification_review_groups'),
        ),
        migrations.AlterField(
            model_name='classification_review',
            name='o_classification',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='classification_review',
            name='schema',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='classification_review',
            name='table_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='classification_review_groups',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
