# Generated by Django 2.0.7 on 2018-09-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0038_auto_20180906_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='category',
            field=models.CharField(default='', max_length=40),
        ),
    ]
