# Generated by Django 2.0.7 on 2018-09-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0039_auto_20180906_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='category',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
