# Generated by Django 2.0.7 on 2018-09-11 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classy', '0040_auto_20180906_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(max_length=200)),
                ('datasource', models.CharField(max_length=100)),
                ('schema', models.CharField(blank=True, max_length=50)),
                ('table', models.CharField(blank=True, max_length=50)),
                ('column', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='classification',
            name='datasource_description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='classification_logs',
            name='n_classification',
            field=models.CharField(choices=[('Unclassified', 'unclassified'), ('PUBLIC', 'public'), ('CONFIDENTIAL', 'confidential'), ('PROTECTED A', 'protected_a'), ('PROTECTED B', 'protected_b'), ('PROTECTED C', 'protected_c')], max_length=50),
        ),
        migrations.AlterField(
            model_name='classification_logs',
            name='o_classification',
            field=models.CharField(choices=[('Unclassified', 'unclassified'), ('PUBLIC', 'public'), ('CONFIDENTIAL', 'confidential'), ('PROTECTED A', 'protected_a'), ('PROTECTED B', 'protected_b'), ('PROTECTED C', 'protected_c')], max_length=50),
        ),
    ]
