# Generated by Django 2.0.7 on 2018-09-11 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classy', '0041_auto_20180911_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissions',
            name='permission',
        ),
    ]
