# Generated by Django 2.0.10 on 2019-02-05 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classy', '0002_auto_20190125_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification_count',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classification',
            name='masking',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classification',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=400),
            preserve_default=False,
        ),
    ]
